import type { ServiceProgram } from "@/types/portal"

export const servicePrograms: Record<string, ServiceProgram> = {
  launch: {
    id: "launch",
    name: "Launch Program",
    persona: "startup-sam",
    description: "Your 60-day journey from idea to first sale",
    color: "bg-green-500",
    icon: "🚀",
    features: [
      "Product Selection Framework",
      "Launch Roadmap & Checklists",
      "Weekly Coach Check-ins",
      "Peer Support Community",
      "Risk Reduction Templates",
    ],
  },
  scale: {
    id: "scale",
    name: "Scale Program",
    persona: "scaling-sarah",
    description: "Systematic business optimization and growth",
    color: "bg-blue-500",
    icon: "📈",
    features: [
      "Business Optimization Project",
      "Operational Excellence Framework",
      "Bi-weekly Strategy Sessions",
      "Advanced Analytics Dashboard",
      "Private Mastermind Access",
    ],
  },
  master: {
    id: "master",
    name: "Master Program",
    persona: "learning-larry",
    description: "Comprehensive Amazon ecosystem mastery",
    color: "bg-purple-500",
    icon: "🎓",
    features: [
      "Complete Course Library",
      "Implementation Exercises",
      "Monthly Expert Mentorship",
      "Knowledge Assessments",
      "Study Group Coordination",
    ],
  },
  invest: {
    id: "invest",
    name: "Invest Program",
    persona: "investor-ian",
    description: "Strategic Amazon business investment guidance",
    color: "bg-amber-500",
    icon: "💼",
    features: [
      "Deal Evaluation Templates",
      "Due Diligence Framework",
      "Investment Opportunity Calendar",
      "Portfolio Tracking Dashboard",
      "Investor Network Access",
    ],
  },
  connect: {
    id: "connect",
    name: "Connect Program",
    persona: "provider-priya",
    description: "Service provider positioning and client acquisition",
    color: "bg-pink-500",
    icon: "🤝",
    features: [
      "Client Acquisition Project",
      "Service Positioning Course",
      "Business Development Sessions",
      "Value Portfolio Builder",
      "Provider Network Community",
    ],
  },
}
